// SEMA-GOVERNED
// M?dulo: sema.produto.orcamento_semantico
// Contrato: contratos/sema/orcamento_semantico.sema
// Descri??o: rule packs e requisitos por preset dos profiles Sema.

import type {
  AchadoProfile,
  CapabilityProfile,
  ConfidenceEngineProfile,
  ConfiancaValidacaoProfile,
  DecisaoAgenteProfile,
  FonteAchadoProfile,
  MaturidadeProfile,
  OpcoesProfileValidar,
  PerfilSemantico,
  PresetProfile,
  ProfileGovernanca,
  RequisitoProfile,
  ResultadoProfileValidar,
  RulePackSema,
  RuntimeGateProfile,
  SeveridadeProfile,
} from "./profileAuthorTipos.js";
export const RULE_PACKS_SEMA: RulePackSema[] = [
  {
    id: "owasp",
    nome: "OWASP Application Security",
    categoria: "premium",
    profiles: ["software"],
    maturidadeMinima: "production",
    controles: ["input_validation", "safe_output", "no_eval", "no_dynamic_sql", "secret_handling"],
    monetizacao: "cloud",
    status: "premium",
  },
  {
    id: "openapi",
    nome: "OpenAPI Contract Surface",
    categoria: "oss",
    profiles: ["software", "workflow"],
    maturidadeMinima: "prototype",
    controles: ["endpoint_shape", "request_response", "auth_surface", "error_contract"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "lgpd",
    nome: "LGPD Privacy Governance",
    categoria: "premium",
    profiles: ["legal", "ops", "workflow"],
    maturidadeMinima: "production",
    controles: ["data_inventory", "legal_basis", "retention", "data_subject_rights", "human_review"],
    monetizacao: "cloud",
    status: "premium",
  },
  {
    id: "dpa",
    nome: "Data Processing Agreement",
    categoria: "premium",
    profiles: ["legal"],
    maturidadeMinima: "production",
    controles: ["controller_processor", "subprocessors", "transfer", "security_measures", "audit"],
    monetizacao: "cloud",
    status: "premium",
  },
  {
    id: "soc2",
    nome: "SOC2 Operational Evidence",
    categoria: "enterprise",
    profiles: ["ops", "workflow", "software", "legal"],
    maturidadeMinima: "critical",
    controles: ["audit_trail", "approval_gate", "incident_evidence", "access_review"],
    monetizacao: "enterprise",
    status: "planejado",
  },
  {
    id: "kubernetes",
    nome: "Kubernetes Change Safety",
    categoria: "premium",
    profiles: ["ops"],
    maturidadeMinima: "production",
    controles: ["deployment_healthcheck", "rollback", "migration_guard", "resource_limits"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "n8n",
    nome: "n8n Workflow Runtime",
    categoria: "premium",
    profiles: ["workflow"],
    maturidadeMinima: "prototype",
    controles: ["node_surface", "credential_boundary", "retry", "idempotency", "dlq"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "saas",
    nome: "Startup SaaS Governance",
    categoria: "premium",
    profiles: ["software", "workflow", "ops", "legal", "research"],
    maturidadeMinima: "production",
    controles: ["authz", "billing_risk", "data_retention", "release_gate", "audit"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "author-quality",
    nome: "Author Quality Gate",
    categoria: "oss",
    profiles: ["author"],
    maturidadeMinima: "draft",
    controles: ["forbidden_literals", "cliche_review", "narrative_conflict", "tone_drift"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "brand-voice",
    nome: "Brand Voice Guardrails",
    categoria: "premium",
    profiles: ["author", "legal", "research", "redacao", "propostas"],
    maturidadeMinima: "prototype",
    controles: ["tone_drift", "style_policy", "forbidden_claims", "approval_review"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "campaign-continuity",
    nome: "Campaign Continuity",
    categoria: "premium",
    profiles: ["author", "game"],
    maturidadeMinima: "production",
    controles: ["canon_memory", "character_state", "promise_tracking", "chapter_drift"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "conversation-safety",
    nome: "Customer Conversation Safety",
    categoria: "oss",
    profiles: ["conversas"],
    maturidadeMinima: "prototype",
    controles: ["forbidden_claims", "tone_policy", "customer_state", "human_handoff", "audit_trace"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "redacao-quality",
    nome: "Redacao Editorial Quality Gate",
    categoria: "oss",
    profiles: ["redacao"],
    maturidadeMinima: "prototype",
    controles: ["pauta", "pesquisa", "seo", "midia_preservada", "voz_nao_generica"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "seo-editorial",
    nome: "SEO Editorial Guardrails",
    categoria: "premium",
    profiles: ["redacao"],
    maturidadeMinima: "production",
    controles: ["search_intent", "meta_description", "headings", "internal_links", "no_keyword_stuffing"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "commercial-proposal",
    nome: "Commercial Proposal Quality Gate",
    categoria: "oss",
    profiles: ["propostas"],
    maturidadeMinima: "prototype",
    controles: ["entregaveis_claros", "persuasao", "nota_interna", "score_minimo_90", "restricoes_marketplace"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "proposal-persuasion",
    nome: "Proposal Persuasion Guardrails",
    categoria: "premium",
    profiles: ["propostas"],
    maturidadeMinima: "production",
    controles: ["dor_cliente", "prova_de_entendimento", "escopo_protegido", "cta_honesto", "sem_enchimento"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "sales-conversation",
    nome: "Sales Conversation Guardrails",
    categoria: "premium",
    profiles: ["conversas"],
    maturidadeMinima: "production",
    controles: ["objection_handling", "authorized_offer", "honest_cta", "no_fake_discount", "promise_limits"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "support-handoff",
    nome: "Support Handoff",
    categoria: "premium",
    profiles: ["conversas", "ops"],
    maturidadeMinima: "production",
    controles: ["escalation_trigger", "ticket_context", "angry_customer", "legal_risk", "handoff_reason"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "event-driven",
    nome: "Event Driven Workflow",
    categoria: "premium",
    profiles: ["workflow", "ops"],
    maturidadeMinima: "production",
    controles: ["event_schema", "idempotency", "retry_policy", "dlq", "compensation"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "approval-flow",
    nome: "Human Approval Flow",
    categoria: "enterprise",
    profiles: ["workflow", "ops", "legal"],
    maturidadeMinima: "critical",
    controles: ["human_gate", "rbac", "audit_trail", "decision_retention"],
    monetizacao: "enterprise",
    status: "planejado",
  },
  {
    id: "sre",
    nome: "SRE Operational Gate",
    categoria: "premium",
    profiles: ["ops"],
    maturidadeMinima: "production",
    controles: ["slo", "error_budget", "runbook", "rollback", "oncall"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "incident-response",
    nome: "Incident Response",
    categoria: "enterprise",
    profiles: ["ops", "legal"],
    maturidadeMinima: "critical",
    controles: ["severity", "communication", "owner", "postmortem", "evidence_retention"],
    monetizacao: "enterprise",
    status: "planejado",
  },
  {
    id: "privacy-policy",
    nome: "Privacy Policy Review",
    categoria: "premium",
    profiles: ["legal"],
    maturidadeMinima: "production",
    controles: ["data_purpose", "legal_basis", "retention", "dpo_contact", "subject_rights"],
    monetizacao: "cloud",
    status: "premium",
  },
  {
    id: "decision-research",
    nome: "Decision Research",
    categoria: "oss",
    profiles: ["research"],
    maturidadeMinima: "prototype",
    controles: ["question", "method", "criteria", "weights", "alternatives"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "contradictory-review",
    nome: "Contradictory Evidence Review",
    categoria: "premium",
    profiles: ["research", "legal"],
    maturidadeMinima: "production",
    controles: ["counter_evidence", "uncertainty", "source_rejection", "confidence_level"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "evidence-matrix",
    nome: "Evidence Matrix",
    categoria: "premium",
    profiles: ["research", "legal"],
    maturidadeMinima: "production",
    controles: ["source_weight", "fact_inference", "reproducibility", "decision_trace"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "playtest",
    nome: "Simulated Playtest",
    categoria: "oss",
    profiles: ["game"],
    maturidadeMinima: "prototype",
    controles: ["first_10_seconds", "first_minute", "tension_point", "reward", "retry_reason"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "economy-balance",
    nome: "Game Economy Balance",
    categoria: "premium",
    profiles: ["game"],
    maturidadeMinima: "production",
    controles: ["currency_source", "sink", "soft_cap", "exploit", "session_curve"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "progression",
    nome: "Progression And Pacing",
    categoria: "premium",
    profiles: ["game", "author"],
    maturidadeMinima: "production",
    controles: ["difficulty_curve", "session_time", "mastery", "frustration", "reward_cadence"],
    monetizacao: "cloud",
    status: "planejado",
  },
  {
    id: "simulation-model",
    nome: "Simulation Model Contract",
    categoria: "oss",
    profiles: ["simulation"],
    maturidadeMinima: "draft",
    controles: ["model", "assumptions", "initial_conditions", "boundary_conditions", "outputs", "units"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "simulation-calibration",
    nome: "Simulation Calibration Evidence",
    categoria: "oss",
    profiles: ["simulation"],
    maturidadeMinima: "prototype",
    controles: ["reference", "calibration", "tolerance", "uncertainty", "telemetry"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "simulation-determinism",
    nome: "Simulation Determinism And Replay",
    categoria: "oss",
    profiles: ["simulation"],
    maturidadeMinima: "prototype",
    controles: ["seed", "fixed_step", "snapshot", "event_log", "replay", "result_digest"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "simulation-batch",
    nome: "Simulation Batch Runs",
    categoria: "oss",
    profiles: ["simulation"],
    maturidadeMinima: "prototype",
    controles: ["replications", "seed_strategy", "aggregation", "resource_budget", "stop_condition"],
    monetizacao: "aberto",
    status: "base",
  },
  {
    id: "simulation-safety",
    nome: "Autonomous Simulation Safety",
    categoria: "oss",
    profiles: ["simulation"],
    maturidadeMinima: "prototype",
    controles: ["authority_boundary", "resource_budget", "stop_condition", "fail_safe", "human_takeover", "isolation"],
    monetizacao: "aberto",
    status: "base",
  },
];

export const REQUISITOS_PRESET_PROFILE: Partial<Record<PresetProfile, RequisitoProfile[]>> = {
  security: [
    { id: "security_entrada_saida", descricao: "declara validacao de entrada e saida segura", termos: [/entrada|input/i, /saida|output|retorno/i, /segur|sanitiz|valid/i], obrigatorio: true, severidade: "blocking" },
  ],
  webhook: [
    { id: "webhook_idempotencia", descricao: "webhook declara idempotencia e retry seguro", termos: [/webhook/i, /idempot/i, /retry|retent/i], obrigatorio: true, severidade: "blocking" },
  ],
  fila: [
    { id: "fila_dlq", descricao: "fila declara erro, retentativa e fila morta", termos: [/fila|queue/i, /erro|falha/i, /dlq|dead.?letter|fila morta/i], obrigatorio: true, severidade: "blocking" },
  ],
  cron: [
    { id: "cron_janela_execucao", descricao: "cron declara janela, concorrencia e reprocessamento", termos: [/cron|agenda/i, /janela|concorr/i, /reprocess|idempot/i], obrigatorio: true, severidade: "blocking" },
  ],
  deploy: [
    { id: "deploy_healthcheck", descricao: "deploy declara healthcheck, rollback e validacao live", termos: [/deploy/i, /healthcheck|healthz/i, /rollback/i], obrigatorio: true, severidade: "blocking" },
  ],
  migration: [
    { id: "migration_reversivel", descricao: "migration declara reversibilidade, backup e criterio de rollback", termos: [/migration|migracao/i, /revers|rollback/i, /backup|snapshot/i], obrigatorio: true, severidade: "critical" },
  ],
  incidente: [
    { id: "incidente_severidade_comunicacao", descricao: "incidente declara severidade, comunicacao e dono", termos: [/incidente|sev/i, /comunic/i, /responsavel|dono/i], obrigatorio: true, severidade: "critical" },
  ],
  rollback: [
    { id: "rollback_criterio_recuperacao", descricao: "rollback declara criterio objetivo de recuperacao", termos: [/rollback/i, /criterio|gatilho/i, /recuper/i], obrigatorio: true, severidade: "blocking" },
  ],
  lgpd: [
    { id: "lgpd_matriz_dados", descricao: "LGPD declara dado, finalidade, base legal e retencao", termos: [/dado|titular/i, /finalidade/i, /base legal/i, /retencao|retenÃ§Ã£o/i], obrigatorio: true, severidade: "critical" },
  ],
  contrato: [
    { id: "contrato_clausulas_nucleo", descricao: "contrato declara partes, objeto, obrigacoes e rescisao", termos: [/partes/i, /objeto/i, /obrigac|obrigaÃ§/i, /rescis/i], obrigatorio: true, severidade: "blocking" },
  ],
  dpa: [
    { id: "dpa_operador_controlador", descricao: "DPA declara controlador, operador, dados e subprocessadores", termos: [/controlador/i, /operador/i, /subprocess/i, /dados/i], obrigatorio: true, severidade: "critical" },
  ],
  termos_uso: [
    { id: "termos_uso_limites", descricao: "termos de uso declaram uso permitido, proibicoes e limitacao", termos: [/uso permitido/i, /proibid|vedad/i, /limitacao|limitaÃ§Ã£o/i], obrigatorio: true, severidade: "blocking" },
  ],
  privacidade: [
    { id: "privacidade_dados_direitos", descricao: "privacidade declara dados, finalidade, direitos e contato", termos: [/dados/i, /finalidade/i, /direitos/i, /contato/i], obrigatorio: true, severidade: "blocking" },
  ],
  due_diligence: [
    { id: "due_diligence_risco_evidencia", descricao: "due diligence declara risco, evidencia e pendencias", termos: [/risco/i, /evidencia|evidÃªncia/i, /pendenc|pendÃªnc/i], obrigatorio: true, severidade: "blocking" },
  ],
  compliance: [
    { id: "compliance_controle_auditoria", descricao: "compliance declara controles, auditoria e responsavel", termos: [/controle/i, /auditoria/i, /responsavel|responsÃ¡vel/i], obrigatorio: true, severidade: "blocking" },
  ],
  decisoria: [
    { id: "research_matriz_decisao", descricao: "pesquisa decisoria declara criterio, peso e alternativa", termos: [/criterio|critÃ©rio/i, /peso/i, /alternativa/i], obrigatorio: true, severidade: "blocking" },
  ],
  critica: [
    { id: "research_contraditorio", descricao: "pesquisa critica tenta derrubar a propria conclusao", termos: [/contradit|contra.?evidencia|contra.?evidÃªncia/i, /hipotese|hipÃ³tese|conclusao|conclusÃ£o/i], obrigatorio: true, severidade: "blocking" },
  ],
  editorial: [
    { id: "redacao_editorial_linha", descricao: "redacao editorial declara linha editorial, publico e objetivo", termos: [/linha editorial|editorial|pauta/i, /publico|objetivo/i], obrigatorio: true, severidade: "blocking" },
  ],
  materia: [
    { id: "redacao_materia_original", descricao: "materia declara original, midia e reescrita final", termos: [/materia_original|materia original/i, /midia|imagem|embed/i, /reescrita|materia_reescrita/i], obrigatorio: true, severidade: "blocking" },
  ],
  blog: [
    { id: "redacao_blog_seo", descricao: "blog declara SEO, headings e meta description", termos: [/blog|artigo|post/i, /seo|headings|meta_description|palavra_chave/i], obrigatorio: true, severidade: "blocking" },
  ],
  seo: [
    { id: "redacao_seo_intencao", descricao: "SEO declara palavra-chave, intencao de busca e anti-keyword stuffing", termos: [/palavra_chave|keyword|seo/i, /intencao_busca|intencao de busca/i, /keyword_stuffing|sem stuffing/i], obrigatorio: true, severidade: "blocking" },
  ],
  reescrita: [
    { id: "redacao_reescrita_sem_plagio", descricao: "reescrita declara preservacao de midia e bloqueio de plagio", termos: [/reescrita|reescrever/i, /midia_preservada|preservar/i, /plagio|sem_plagio/i], obrigatorio: true, severidade: "critical" },
  ],
  marketplace: [
    { id: "propostas_marketplace_restricoes", descricao: "proposta de marketplace respeita plataforma e contato externo", termos: [/99freelas|workana|marketplace/i, /restricoes_plataforma|contato_externo|sem contato externo/i], obrigatorio: true, severidade: "blocking" },
  ],
  freela: [
    { id: "propostas_freela_escopo", descricao: "proposta freela declara escopo minimo, entregaveis e risco", termos: [/escopo_minimo|escopo minimo|escopo/i, /entregaveis?|entrega/i, /risco|furada/i], obrigatorio: true, severidade: "blocking" },
  ],
  consultiva: [
    { id: "propostas_consultiva_dor", descricao: "proposta consultiva mostra dor do cliente e estrategia de fechamento", termos: [/dor_cliente|dor do cliente|problema/i, /estrategia_fechamento|fechamento|proxima acao/i], obrigatorio: true, severidade: "blocking" },
  ],
  diagnostico: [
    { id: "propostas_diagnostico_sem_linguica", descricao: "diagnostico comercial e direto e sem enchimento", termos: [/diagnostico|analise/i, /direta|sem_linguica|sem enrolacao|objetiva/i], obrigatorio: true, severidade: "blocking" },
  ],
  score90: [
    { id: "propostas_score90_gate", descricao: "proposta so fica pronta com score minimo 90", termos: [/score_final_proposta|score/i, />=\s*90|90/i, /pronta_para_enviar|aprovar_score_abaixo_90/i], obrigatorio: true, severidade: "critical" },
  ],
  playtest: [
    { id: "game_playtest_temporal", descricao: "playtest declara primeiros segundos, primeiro minuto e tensao", termos: [/primeiros? 10 segundos|10s/i, /1 minuto|um minuto/i, /tensao|tensÃ£o/i], obrigatorio: true, severidade: "blocking" },
  ],
  economia: [
    { id: "game_economia_balanceada", descricao: "economia declara moeda, fonte, gasto e exploit", termos: [/moeda|economia/i, /fonte/i, /gasto|sink/i, /exploit/i], obrigatorio: true, severidade: "blocking" },
  ],
  model: [
    { id: "simulation_model_core", descricao: "modelo declara assumptions, condicoes, outputs e unidades", termos: [/modelo|model/i, /assumptions?|premissas?/i, /condicoes?_iniciais|initial[_ -]?conditions?/i, /condicoes?_contorno|boundary[_ -]?conditions?/i, /outputs?|saidas?/i, /unidades?|units?/i], obrigatorio: true, severidade: "blocking" },
  ],
  scenario: [
    { id: "simulation_scenario_acceptance", descricao: "cenario declara identidade, condicoes e criterios de aceitacao", termos: [/scenario|cenario/i, /condicoes?_iniciais|initial[_ -]?conditions?/i, /condicoes?_contorno|boundary[_ -]?conditions?/i, /acceptance|aceitacao|resultado_esperado/i], obrigatorio: true, severidade: "blocking" },
  ],
  calibration: [
    { id: "simulation_calibration_evidence", descricao: "calibracao declara referencia, metodo, tolerancia, incerteza e telemetria", termos: [/referencia|reference|dataset/i, /calibracao|calibration/i, /tolerancias?|tolerances?/i, /incerteza|uncertainty/i, /telemetria|telemetry/i], obrigatorio: true, severidade: "critical" },
  ],
  deterministic: [
    { id: "simulation_deterministic_replay", descricao: "determinismo declara seed, passo, snapshot e replay", termos: [/determinism|determinismo|deterministic/i, /seed/i, /fixed[_ -]?step|passo_reprodutivel/i, /snapshot|state[_ -]?digest/i, /replay|event[_ -]?log/i], obrigatorio: true, severidade: "blocking" },
  ],
  batch: [
    { id: "simulation_batch_budget", descricao: "batch declara repeticoes, estrategia de seeds, agregacao, budget e parada", termos: [/batch|lote|ensemble/i, /replications?|repeticoes?|scenarios?/i, /seed[_ -]?strategy|estrategia[_ -]?seed/i, /aggregation|agregacao|metricas?/i, /budget|orcamento|limite/i, /stop[_ -]?condition|criterio[_ -]?parada/i], obrigatorio: true, severidade: "blocking" },
  ],
  safety: [
    { id: "simulation_autonomous_safety", descricao: "autonomia declara fronteira, budget, parada, fail-safe e tomada humana", termos: [/autonomous|uncontrolled|autonom/i, /authority[_ -]?boundary|fronteira[_ -]?autoridade/i, /resource[_ -]?budget|orcamento[_ -]?recursos|limite/i, /stop[_ -]?condition|criterio[_ -]?parada|kill[_ -]?switch/i, /fail[_ -]?safe|human[_ -]?takeover|isolamento/i], obrigatorio: true, severidade: "critical" },
  ],
  atendimento: [
    { id: "conversas_atendimento_estado", descricao: "atendimento declara estado do cliente e proxima acao", termos: [/estado|etapa|sentimento/i, /proxima_acao|proxima acao|encaminhar|resolver/i], obrigatorio: true, severidade: "blocking" },
  ],
  vendas: [
    { id: "conversas_vendas_objecao_cta", descricao: "vendas trata objecao e CTA sem promessa falsa", termos: [/objec|duvida|interesse|dor/i, /cta|proxima_acao|proxima acao|agendar|diagnostico|proposta/i], obrigatorio: true, severidade: "blocking" },
  ],
  suporte: [
    { id: "conversas_suporte_escalacao", descricao: "suporte declara problema, solucao e escalacao humana", termos: [/problema|erro|suporte|chamado/i, /escalar|humano|atendente|ticket/i], obrigatorio: true, severidade: "blocking" },
  ],
  qualificacao: [
    { id: "conversas_qualificacao_criterios", descricao: "qualificacao declara criterios e dados minimos do lead", termos: [/qualifica|lead|perfil/i, /criterio|orcamento|prazo|necessidade/i], obrigatorio: true, severidade: "blocking" },
  ],
  retencao: [
    { id: "conversas_retencao_limites", descricao: "retencao declara motivo, proposta autorizada e limites", termos: [/retencao|cancelamento|motivo/i, /autorizad|limite|oferta|proposta/i], obrigatorio: true, severidade: "blocking" },
  ],
  cobranca: [
    { id: "conversas_cobranca_cuidado", descricao: "cobranca declara valor, vencimento, tom e escalacao", termos: [/cobranca|valor|vencimento/i, /tom|respeitoso|humano|escalar/i], obrigatorio: true, severidade: "critical" },
  ],
};
