arquivo             = modulo ;
modulo              = "module" identificador "{" declaracao_modulo* "}" ;
declaracao_modulo   = use | docs | comments | vinculos | type | entity | enum | task | flow | route | worker | evento | fila | cron | webhook | cache | storage | policy | state | tests ;
use                 = "use" identificador ;
type                = "type" identificador bloco_generico ;
entity              = "entity" identificador bloco_generico ;
enum                = "enum" identificador "{" identificador ("," identificador)* "}" ;
task                = "task" identificador bloco_generico ;
flow                = "flow" identificador bloco_generico ;
route               = "route" identificador bloco_generico ;
worker              = "worker" identificador bloco_generico ;
evento              = "evento" identificador bloco_generico ;
fila                = "fila" identificador bloco_generico ;
cron                = "cron" identificador bloco_generico ;
webhook             = "webhook" identificador bloco_generico ;
cache               = "cache" identificador bloco_generico ;
storage             = "storage" identificador bloco_generico ;
policy              = "policy" identificador bloco_generico ;
state               = "state" bloco_generico ;
tests               = "tests" "{" caso* "}" ;
caso                = "caso" texto "{" given? when? expect? error? docs? comments? "}" ;
given               = "given" bloco_generico ;
when                = "when" bloco_generico ;
expect              = "expect" bloco_generico ;
error               = "error" bloco_generico ;
vinculos            = "vinculos" bloco_generico ;
docs                = "docs" bloco_generico ;
comments            = "comments" bloco_generico ;
bloco_generico      = "{" item_bloco* "}" ;
item_bloco          = campo | linha | bloco_generico_nomeado ;
bloco_generico_nomeado = palavra_chave "{" item_bloco* "}" ;
campo               = identificador ":" valor valor_modificador* ;
linha               = valor+ ;
valor               = identificador | numero | texto ;
valor_modificador   = identificador ;
identificador       = ? token de identificador ? ;
numero              = ? token numerico ? ;
texto               = ? token textual ? ;
palavra_chave       = "input" | "output" | "rules" | "effects" | "impl" | "vinculos" | "execucao" | "guarantees" | "state" | "fields" | "tests" | "error" | "docs" | "comments" | "given" | "when" | "expect" ;
